#!/usr/bin/ruby

require 'pp'
require 'fileutils'
include FileUtils

desc 'Check git'
task :git do 
  sh "/usr/bin/git diff --exit-code --quiet" do |ok,res|
    if !ok
      sh "git status"
#      fail "Uncommited local changes, please fix with 'git add' etc."
    end
  end
end

desc 'Build yabasic.exe'
task :build_yabasic => :git do
  sh '/cygdrive/c/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe','c:/work/yabasic/windows/yabasic.sln'
end

vs=Hash.new
desc 'Collect Versions'
task :versions => :build_yabasic do
  File.open('start.bat','w') {|f| f.puts %x( cygpath lang/Release/yabasic.exe ) + " --version >yabasic.out 2>&1"}
  sh "cygstart start.bat"
  vs['yabasic']=File.new('yabasic.out').read.match(/yabasic (\d\.\d+\.\d+)/ )[1]
  pp vs
end

desc 'Show products'
task :default => :versions do
  sh 'ls -l ../products'
end
