//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch yabinst.rc
//
#define IDD_PATHDIALOG 101
#define IDD_PROGRESSDIALOG 102
#define IDI_ICON1 103
#define IDD_ON_SUCCESS 108
#define IDD_ON_ERROR 111
#define IDINSTPATH 1000
#define IDC_PROGRESSTEXT 1002
#define IDC_BROWSE 1005
#define IDC_BUTTON_JUST_EXIT 1012
#define IDC_BUTTON_RUN_DEMO 1015
#define IDC_BUTTON_READ_DOCU 1016
#define IDC_BUTTON_VIEW_LOG 1017
#define IDC_BUTTON_READ_DOCU2 1017
#define IDC_BUTTON_VIEW_LOG2 1017
#define IDC_ERRORTEXT 1018
#define IDC_SUCCESSTEXT 1019

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 113
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1020
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
