#!/bin/bash 

echo
echo Transforming yabasic.xml to html
echo
set -x

export SGML_CATALOG_FILES=/etc/xml/catalog
xsltproc mystyle.xsl yabasic.xml >yabasic.htm
cp yabasic.htm ../yabmain/yabasic.htm
cp yabasic.xml ../yabmain/yabasic.xml

echo
echo yabasic.xml to yabwrap.htm
echo
./a2h yabasic.xml >yabwrap.htm

echo
echo yabasic.htm to yabasic.1
echo
perl yabasic_to_man


